shfmt: tweak configuration to match old style
Signed-off-by: Sebastiaan van Stijn <github@gone.nl>

diff --git a/contrib/init/sysvinit-debian/docker b/contrib/init/sysvinit-debian/docker
--- a/contrib/init/sysvinit-debian/docker
+++ b/contrib/init/sysvinit-debian/docker
@@ -46,7 +46,7 @@ fi
 
 check_init() {
 	# see also init_is_upstart in /lib/lsb/init-functions (which isn't available in Ubuntu 12.04, or we'd use it directly)
-	if [ -x /sbin/initctl ] && /sbin/initctl version 2>/dev/null | grep -q upstart; then
+	if [ -x /sbin/initctl ] && /sbin/initctl version 2> /dev/null | grep -q upstart; then
 		log_failure_msg "$DOCKER_DESC is managed via upstart, try using service $BASE $1"
 		exit 1
 	fi
@@ -61,9 +61,9 @@ fail_unless_root() {
 
 cgroupfs_mount() {
 	# see also https://github.com/tianon/cgroupfs-mount/blob/master/cgroupfs-mount
-	if grep -v '^#' /etc/fstab | grep -q cgroup ||
-		[ ! -e /proc/cgroups ] ||
-		[ ! -d /sys/fs/cgroup ]; then
+	if grep -v '^#' /etc/fstab | grep -q cgroup \
+		|| [ ! -e /proc/cgroups ] \
+		|| [ ! -d /sys/fs/cgroup ]; then
 		return
 	fi
 	if ! mountpoint -q /sys/fs/cgroup; then
@@ -83,74 +83,74 @@ cgroupfs_mount() {
 }
 
 case "$1" in
-start)
-	check_init
+	start)
+		check_init
 
-	fail_unless_root
+		fail_unless_root
 
-	cgroupfs_mount
+		cgroupfs_mount
 
-	touch "$DOCKER_LOGFILE"
-	chgrp docker "$DOCKER_LOGFILE"
+		touch "$DOCKER_LOGFILE"
+		chgrp docker "$DOCKER_LOGFILE"
 
-	ulimit -n 1048576
+		ulimit -n 1048576
 
-	# Having non-zero limits causes performance problems due to accounting overhead
-	# in the kernel. We recommend using cgroups to do container-local accounting.
-	if [ "$BASH" ]; then
-		ulimit -u unlimited
-	else
-		ulimit -p unlimited
-	fi
+		# Having non-zero limits causes performance problems due to accounting overhead
+		# in the kernel. We recommend using cgroups to do container-local accounting.
+		if [ "$BASH" ]; then
+			ulimit -u unlimited
+		else
+			ulimit -p unlimited
+		fi
 
-	log_begin_msg "Starting $DOCKER_DESC: $BASE"
-	start-stop-daemon --start --background \
-		--no-close \
-		--exec "$DOCKERD" \
-		--pidfile "$DOCKER_SSD_PIDFILE" \
-		--make-pidfile \
-		-- \
-		-p "$DOCKER_PIDFILE" \
-		$DOCKER_OPTS \
-		>>"$DOCKER_LOGFILE" 2>&1
-	log_end_msg $?
-	;;
-
-stop)
-	check_init
-	fail_unless_root
-	if [ -f "$DOCKER_SSD_PIDFILE" ]; then
-		log_begin_msg "Stopping $DOCKER_DESC: $BASE"
-		start-stop-daemon --stop --pidfile "$DOCKER_SSD_PIDFILE" --retry 10
+		log_begin_msg "Starting $DOCKER_DESC: $BASE"
+		start-stop-daemon --start --background \
+			--no-close \
+			--exec "$DOCKERD" \
+			--pidfile "$DOCKER_SSD_PIDFILE" \
+			--make-pidfile \
+			-- \
+			-p "$DOCKER_PIDFILE" \
+			$DOCKER_OPTS \
+			>> "$DOCKER_LOGFILE" 2>&1
 		log_end_msg $?
-	else
-		log_warning_msg "Docker already stopped - file $DOCKER_SSD_PIDFILE not found."
-	fi
-	;;
+		;;
 
-restart)
-	check_init
-	fail_unless_root
-	docker_pid=$(cat "$DOCKER_SSD_PIDFILE" 2>/dev/null)
-	[ -n "$docker_pid" ] &&
-		ps -p $docker_pid >/dev/null 2>&1 &&
-		$0 stop
-	$0 start
-	;;
+	stop)
+		check_init
+		fail_unless_root
+		if [ -f "$DOCKER_SSD_PIDFILE" ]; then
+			log_begin_msg "Stopping $DOCKER_DESC: $BASE"
+			start-stop-daemon --stop --pidfile "$DOCKER_SSD_PIDFILE" --retry 10
+			log_end_msg $?
+		else
+			log_warning_msg "Docker already stopped - file $DOCKER_SSD_PIDFILE not found."
+		fi
+		;;
 
-force-reload)
-	check_init
-	fail_unless_root
-	$0 restart
-	;;
+	restart)
+		check_init
+		fail_unless_root
+		docker_pid=$(cat "$DOCKER_SSD_PIDFILE" 2> /dev/null)
+		[ -n "$docker_pid" ] \
+			&& ps -p $docker_pid > /dev/null 2>&1 \
+			&& $0 stop
+		$0 start
+		;;
 
-status)
-	check_init
-	status_of_proc -p "$DOCKER_SSD_PIDFILE" "$DOCKERD" "$DOCKER_DESC"
-	;;
+	force-reload)
+		check_init
+		fail_unless_root
+		$0 restart
+		;;
 
-*)
-	echo "Usage: service docker {start|stop|restart|status}"
-	exit 1
-	;;
+	status)
+		check_init
+		status_of_proc -p "$DOCKER_SSD_PIDFILE" "$DOCKERD" "$DOCKER_DESC"
+		;;
+
+	*)
+		echo "Usage: service docker {start|stop|restart|status}"
+		exit 1
+		;;
 esac
